from enum import Enum


class BattlePhase(Enum):
    COMMAND = 0
    MOVEMENT = 1
    SHOOTING = 2
    CHARGE = 3
    FIGHT = 4
    BATTLESHOCK = 5


class Pos(Enum):
    POS_START = 0
    HITS_START = 100
    HITS_CHECK_SUCCESS_CRITERIA = 101
    HITS_REROLL = 102
    HITS_APPLY_CRIT_EFFECTS = 103
    HITS_END = 104
    WOUNDS_START = 200
    WOUNDS_CHECK_SUCCESS_CRITERIA = 201
    WOUNDS_REROLL = 202
    WOUNDS_APPLY_CRIT_EFFECTS = 203
    WOUNDS_END = 204
    SAVES_START = 300
    SAVES_CHECK_SUCCESS_CRITERIA = 301
    SAVES_REROLL = 302
    SAVES_APPLY_CRIT_EFFECTS = 303
    SAVES_END = 304
    FNP_START = 400
    FNP_CALCULATE_TOTAL_DAMAGE = 401
    FNP_CHECK_SUCCESS_CRITERIA = 402
    FNP_REROLL = 403
    FNP_APPLY_CRIT_EFFECTS = 404
    FNP_END = 405
    DMG_START = 500
    DMG_INSTANCE_OF_DAMAGE = 501
    DMG_MODEL_KILLED = 502
    DMG_END = 503
    POS_END = 999
